### ISSUE TITLE
array_parallelism for LocalExecutor

### ISSUE THREAD

**Issue by se-ok** [facebookincubator/submitit#1718] opened 2022-10-26 05:24 UTC
When using job arrays, SlurmExecutor may limit the number of concurrent jobs running via `array_parallelism` parameter.
However, it seems to me LocalExecutor does not have the corresponding functionality.
Would it be meaningful to add an option to LocalExecutor which limits the number of concurrently running jobs?
Would it be too cumbersome to make `PicklingExecutor._internal_process_submissions` limit the concurrent jobs without problems?

## Use case
- A big job is partitioned into many smaller jobs
- The slurm queue is full with many pending jobs
- Would like to use the same codebase using submitit in a separate compute environment without slurm, with minimal code changes

## Current solution
- Use ThreadPoolExecutor, where the workers run a function which creates its own LocalExecutor, submit, and wait until finishes.
- And the pool controls the number of concurrent jobs

## Suggestion
- The following code to execute without running more than 5 jobs concurrently
```python
executor = LocalExecutor(folder=somewhere)
executor.update_parameters(array_parallelism=5)

with executor.batch():
    ...
```

**Comment by gwenzek** [comment] 2023-03-02 14:11
`LocalExecutor` really needs something like this. PR most welcome.

**Comment by gwenzek** [comment] 2023-03-02 14:24
duplicate of #1685

**Closed by gwenzek** 2023-03-02 14:24 UTC
